Add all features for peer review
benshidanny11/task-manager pull request #1
Opened 2021-09-27 12:41 UTC by benshidanny11

## Add and remove implementation
>In this milestone I
- Added all features(Display all tasks, Add task, Update task, and Delete task)

2021-09-27 14:23 UTC, Gambit142 commented on src/utils.js
> +  localStorage.setItem('todos', JSON.stringify(todos));
Hi @benshidanny11,

Great Work implementing the CRUD function, I like the fact that you follow best practices for HTML, CSS, and JavaScript.

In this code snippet, you repeated the statement that stores your objects in the local storage and the `window.location.reload()` function. Part of JavaScript practices is to try and make your code as **_DRY_** as possible.
So I will suggest that you put it in a function and call it in when you need it.

I hope to collaborate with you in the future. Happy Coding 👍

2021-09-27 14:25 UTC, Gambit142 commented on src/utils.js
> +  window.location.reload();
Hi @benshidanny11,

Great Work implementing the CRUD function, I like the fact that you follow best practices for HTML, CSS, and JavaScript.

In this code snippet, you repeated the statement that stores your objects in the local storage and the `window.location.reload()` function. Part of JavaScript practices is to try and make your code as **_DRY_** as possible.
So I will suggest that you put it in a function and call it in when you need it.

I hope to collaborate with you in the future. Happy Coding 👍

2021-09-27 14:26 UTC, Gambit142 commented on src/utils.js
> +    localStorage.setItem('todos', JSON.stringify(remainingTodos));
Hi, Please check the comments above

2021-09-27 14:31 UTC, Gambit142 requested changes
## Changes Required ♻️ 

Great job!! @benshidanny11, 

Your work is well documented and you were professional in creating it.

However, there are few changes to be made. Kindly check the comments below to see where necessary changes can be made.

Please do reach out to me if you have any questions or if you need further clarifications.

2021-09-27 14:31 UTC, Gambit142 commented on src/utils.js
> +    localStorage.setItem('todos', JSON.stringify(remainingTodos));
Please check the first comment

2021-09-27 21:02 UTC, benshidanny11 commented
Thank you @Gambit142, I really appreciate your feedback and I am going to work on them :+1:

2021-09-28 07:48 UTC, Gambit142 approved these changes
## PROJECT APPROVED ✔️ 

Hi @benshidanny11 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Happy Coding 👏 👏

2021-09-28 07:51 UTC, merged